### ISSUE TITLE
Build fail - Undefined reference to devMAX11300()

### ISSUE THREAD

**Issue by richardhenryhopper** [physical-computation/Warp-firmware#72]
Build fail from commit/bbadcf9db2dc6d462d6076fa8db33e47a89b6b92
Undefined reference to devMAX11300 (line 2077) of warp-kl03-ksdk1.1-boot.c.obj

**Comment by JamesTimothyMeech** [comment]
This happens because MAX11300.c isn't included in CMakeLists.txt. Including MAX11300.c in CMakeLists.txt leads to another error because MAX11300.c references code in devSSD1331.c which is also not included in CMakeLists.txt. 

Solution to be implemented: Move code referenced in devSSD1331.c into MAX11300.c and use if defs to allow MAX11300.c code to be ignored for normal use of the firmware

**Comment by phillipstanleymarbell** [comment]
Should be fixed in c4ca022762d1e5ae14a9ede1d29673d799d7275d
